### ISSUE TITLE
Missing dependency in alert-dialog

### ISSUE THREAD

**Issue by csellis** [reach/reach-ui#133]
Missing dependency on alert-dialog

```
Cannot find module "@reach/utils/lib/IdContext"
Error: Cannot find module "@reach/utils/lib/IdContext"
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:62316:7)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:679:30)
    at fn (http://localhost:9001/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:58004:69)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:679:30)
    at fn (http://localhost:9001/static/preview.bundle.js:89:20)
    at webpackContext (http://localhost:9001/static/preview.bundle.js:57976:9)
    at http://localhost:9001/static/preview.bundle.js:54640:16
    at Array.forEach (<anonymous>)
    at http://localhost:9001/static/preview.bundle.js:54639:14
ERROR in ./packages/alert-dialog/src/index.js
Module not found: Error: Can't resolve '@reach/utils/lib/IdContext' in '/home/chris/Projects/reach-ui/packages/alert-dialog/src'
```

**Comment by erikiva** [comment]
I run into this, when I was looking into another issue, seems like lib was deleted at some point. I tried adding the lib directory and the deleted file with the IdContext but I am still getting the issue, not sure what I am missing.

**Comment by Kerumen** [comment]
It has been deleted here: https://github.com/reach/reach-ui/commit/6e21b177eda2f74e50d912f98d83d6ef277c80e2#diff-61be82a404b0af0dc9fa6f4ee03653f2L1

@ryanflorence Is there a specific reason? Did you forget something?

**Comment by chancestrickland** [comment]
We are not using that dependency anywhere in the project anymore as far as I can tell. I wouldn't advise using @reach/utils as a standalone package -- it's intended for shared utilities used in different components in the project and is likely see changes like this over time.
