### ISSUE TITLE
MenuItem tests call the wrong callback

### ISSUE THREAD

**Issue by llimllib** [reach/reach-ui#833]
### Current Behavior

testing a click on the second item in a Menu does not work as expected; the callback for the first item is fired instead.

### Expected behavior

In https://github.com/reach/reach-ui/blob/develop/packages/menu-button/__tests__/menu-button.test.tsx#L123 , there is a test that the callback for a menu item has been called.

If you add a test that tries to click the _second_ item, as in this diff: https://github.com/reach/reach-ui/compare/develop...llimllib:llimllib-menu-item-test

you'll find that the test fails, and the callback for the _first_ item has been called instead of the second:

<details>
  <summary>test output</summary>
<pre>
$ jest packages/menu-button/__tests__/menu-button.test.tsx
 FAIL  packages/menu-button/__tests__/menu-button.test.tsx
  <MenuButton /> with <MenuItem />
    a11y
      ARIA attributes
        ✓ `role` is set to `menu` for list element (44 ms)
        ✓ `aria-controls` for button element points to the list element id (18 ms)
        ✓ `aria-haspopup` for button element is present (12 ms)
        when the list is not toggled
          ✓ `aria-expanded` for the button element is not present (11 ms)
        when the list is toggled
          ✓ `role` is set to `menuitem` for item elements (12 ms)
          ✓ `aria-expanded` for the button element is true (14 ms)
          ✓ `aria-labelledby` for list element points to the button element id (12 ms)
          ✓ `aria-activedescendant` for list element is not present (9 ms)
          when mouse enters an item
            ✓ `aria-activedescendant` for list element points to the active item (11 ms)
    rendering
      ✓ passes DOM props to the button (7 ms)
      ✓ should not show the menu list by default (7 ms)
    user events
      ✓ should show the list when the button is clicked (17 ms)
      ✓ should call `onSelect` when user selects an item (11 ms)
      ✕ should call `onSelect` for the second item when user selects the second item (12 ms)
      ✓ should not focus the button when user selects an item with click (15 ms)
      ✓ should manage focus when user selects an item with `Space` key (12 ms)
      ✓ should manage focus when user selects an item with `Enter` key (11 ms)
      ✓ should manage focus when user dismisses with the `Escape` key (14 ms)
      ✓ should not manage focus when user clicks outside element (10 ms)

  ● <MenuButton /> with <MenuItem /> › user events › should call `onSelect` for the second item when user selects the second item

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 0
    Received number of calls: 1

      129 |       simulateSpaceKeyClick(rendered.button, { fireClick: true });
      130 |       simulateSpaceKeyClick(rendered.items[1], { fireClick: true });
    > 131 |       expect(rendered.selectCallbacks[0]).toHaveBeenCalledTimes(0);
          |                                           ^
      132 |       expect(rendered.selectCallbacks[1]).toHaveBeenCalledTimes(1);
      133 |     });
      134 |

      at Object.<anonymous> (packages/menu-button/__tests__/menu-button.test.tsx:131:43)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 18 passed, 19 total
Snapshots:   0 total
Time:        3.565 s, estimated 5 s
</pre>
</details>

### Reproducible example

Run the tests on my branch: https://github.com/llimllib/reach-ui/tree/llimllib-menu-item-test

### Suggested solution(s)

I don't know why this is happening, I'm not a react expert I'm just trying to upgrade reach-ui on an app that I didn't write and I have run into an analagous issue that's blocking me because I can't get the tests to pass.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |   0ae8332      |
| React            |         |    whatever 0ae8332 installs     |
| Browser          |         |    N/A    |
| Assistive tech   |         |   N/A      |
| Node             |         |     16.3.0    |
| npm/yarn         |         |    1.22.11     |
| Operating System |         |   OS X Big Sur     |

**Comment by llimllib** [comment]
Using `simulateMouseClick` instead of `simulateSpaceKeyClick` yields the same results
